<?php
require('../modelo/conexion.php');
$id_carga=$_POST['id'];

$ObsAC=$_POST['ObsAC'];
$debeAC=$_POST['debeAC'];
$haberAC=$_POST['haberAC'];
$debeDolAC=$_POST['debeDolAC'];
$haberDolAC=$_POST['haberDolAC'];
$ObsAT=$_POST['ObsAT'];

$ObsFT=$_POST['ObsFT'];

$ObsL=$_POST['ObsL'];
$debeL=$_POST['debeL'];
$haberL=$_POST['haberL'];
$debeDolL=$_POST['debeDolL'];
$haberDolL=$_POST['haberDolL'];
$obsFT=$_POST['ObsFT'];
$debeFT=$_POST['debeFT'];
$haberFT=$_POST['haberFT'];
$debeDolFT=$_POST['debeDolFT'];
$haberDolFT=$_POST['haberDolFT'];
$ObsTHC=$_POST['ObsTHC'];
$debeTHC=$_POST['debeTHC'];
$haberTHC=$_POST['haberTHC'];
$debeDolTHC=$_POST['debeDolTHC'];
$haberDolTHC=$_POST['haberDolTHC'];
$ObsC=$_POST['ObsC'];
$debeC=$_POST['debeC'];
$haberC=$_POST['haberC'];
$debeDolC=$_POST['debeDolC'];
$haberDolC=$_POST['haberDolC'];
$ObsEDF=$_POST['ObsEDF'];
$debeEDF=$_POST['debeEDF'];
$haberEDF=$_POST['haberEDF'];
$debeDolEDF=$_POST['debeDolEDF'];
$haberDolEDF=$_POST['haberDolEDF'];
$ObsGI=$_POST['ObsGI'];
$debeGI=$_POST['debeGI'];
$haberGI=$_POST['haberGI'];
$debeDolGI=$_POST['debeDolGI'];
$haberDolGI=$_POST['haberDolGI'];
$ObsGO=$_POST['ObsGO'];
$debeGO=$_POST['debeGO'];
$haberGO=$_POST['haberGO'];
$debeDolGO=$_POST['debeDolGO'];
$haberDolGO=$_POST['haberDolGO'];
$ObsTD=$_POST['ObsTD'];
$debeTD=$_POST['debeTD'];
$haberTD=$_POST['haberTD'];
$debeDolTD=$_POST['debeDolTD'];
$haberDolTD=$_POST['haberDolTD'];
$ObsPCont=$_POST['ObsPCont'];
$debePCont=$_POST['debePCont'];
$haberPCont=$_POST['haberPCont'];
$debeDolPCont=$_POST['debeDolPCont'];
$haberDolPCont=$_POST['haberDolPCont'];
$ObsDC=$_POST['ObsDC'];
$debeDC=$_POST['debeDC'];
$haberDC=$_POST['haberDC'];
$debeDolDC=$_POST['debeDolDC'];
$haberDolDC=$_POST['haberDolDC'];
$ObsG=$_POST['ObsG'];
$debeG=$_POST['debeG'];
$haberG=$_POST['haberG'];
$debeDolG=$_POST['debeDolG'];
$haberDolG=$_POST['haberDolG'];
$ObsA=$_POST['ObsA'];
$debeA=$_POST['debeA'];
$haberA=$_POST['haberA'];
$debeDolA=$_POST['debeDolA'];
$haberDolA=$_POST['haberDolA'];
$ObsPC=$_POST['ObsPC'];
$debePC=$_POST['debePC'];
$haberPC=$_POST['haberPC'];
$debeDolPC=$_POST['debeDolPC'];
$haberDolPC=$_POST['haberDolPC'];
$ObsDP=$_POST['ObsDP'];
$debeDP=$_POST['debeDP'];
$haberDP=$_POST['haberDP'];
$debeDolDP=$_POST['debeDolDP'];
$haberDolDP=$_POST['haberDolDP'];
$ObsPAA=$_POST['ObsPAA'];
$debePAA=$_POST['debePAA'];
$haberPAA=$_POST['haberPAA'];
$debeDolPAA=$_POST['debeDolPAA'];
$haberDolPAA=$_POST['haberDolPAA'];
$ObsAlm=$_POST['ObsAlm'];
$debeAlm=$_POST['debeAlm'];
$haberAlm=$_POST['haberAlm'];
$debeDolAlm=$_POST['debeDolAlm'];
$haberDolAlm=$_POST['haberDolAlm'];
$ObsTra=$_POST['ObsTra'];
$debeTra=$_POST['debeTra'];
$haberTra=$_POST['haberTra'];
$debeDolTra=$_POST['debeDolTra'];
$haberDolTra=$_POST['haberDolTra'];
$ObsEst=$_POST['ObsEst'];
$debeEst=$_POST['debeEst'];
$haberEst=$_POST['haberEst'];
$debeDolEst=$_POST['debeDolEst'];	
$haberDolEst=$_POST['haberDolEst'];
$ObsOtro=$_POST['ObsOtros'];
$debeOtro=$_POST['debeOtros'];
$haberOtro=$_POST['debeOtros'];
$debeDolOtro=$_POST['debeDolOtros'];
$haberDolOtro=$_POST['haberDolOtros'];
$ObsCC=$_POST['ObsCC'];
$debeCC=$_POST['debeCC'];
$haberCC=$_POST['haberCC'];
$debeDolCC=$_POST['debeDolCC'];
$haberDolCC=$_POST['haberDolCC'];
$ObsFTrans=$_POST['ObsFTrans'];
$debeFTrans=$_POST['debeFTrans'];
$haberFTrans=$_POST['haberFTrans'];
$debeDolFTrans=$_POST['debeDolFTrans'];
$haberDolFTrans=$_POST['haberDolFTrans'];
$ObsTHD=$_POST['ObsTHD'];
$debeTHD=$_POST['debeTHD'];
$haberTHD=$_POST['haberTHD'];
$debeDolTHD=$_POST['debeDolTHD'];
$haberDolTHD=$_POST['haberDolTHD'];
$ObsEDS=$_POST['ObsEDS'];
$debeEDS=$_POST['debeEDS'];
$haberEDS=$_POST['haberEDS'];
$debeDolEDS=$_POST['debeDolEDS'];
$haberDolEDS=$_POST['haberDolEDS'];
$ObsCG=$_POST['ObsCG'];
$debeCG=$_POST['debeCG'];
$haberCG=$_POST['haberCG']; 
$debeDolCG=$_POST['debeDolCG']; 
$haberDolCG=$_POST['haberDolCG']; 
$ObsEDS=$_POST['ObsEDS']; 
$debeEDS=$_POST['debeEDS']; 
$haberEDS=$_POST['haberEDS']; 
$debeDolEDS=$_POST['debeDolEDS'];
$haberDolEDS=$_POST['haberDolEDS']; 
$ObsTHD=$_POST['ObsTHD'];
$debeTHD=$_POST['debeTHD']; 	
$haberTHD=$_POST['haberTHD']; 
$debeDolTHD=$_POST['debeDolTHD']; 
$haberDolTHD=$_POST['haberDolTHD'];
$ObsCP=$_POST['ObsCP'];
 
$query="UPDATE notaContables SET 
ObsAC='$ObsAC',debeAC='$debeAC',haberAC='$haberAC',debeDolAC='$debeDolAC',haberDolAC='$haberDolAC',
ObsAT='$ObsAT',ObsFT='$ObsFT',
ObsL='$ObsL',debeL='$debeL',haberL='$haberL',debeDolL='$debeDolL',haberDolL='$haberDolL',
ObsFT='$obsFT',debeFT='$debeFT',haberFT='$haberFT',debeDolFT='$debeDolFT',haberDolFT='$haberDolFT',
ObsTHC='$ObsTHC',debeTHC='$debeTHC',haberTHC='$haberTHC',debeDolTHC='$debeDolTHC',haberDolTHC='$haberDolTHC',
ObsC='$ObsC',debeC='$debeC',haberC='$haberC',debeDolC='$debeDolC',haberDolC='$haberDolC',
ObsEDF='$ObsEDF',debeEDF='$debeEDF',haberEDF='$haberEDF',debeDolEDF='$debeDolEDF',haberDolEDF='$haberDolEDF',
ObsGI='$ObsGI',debeGI='$debeGI',haberGI='$haberGI',debeDolGI='$debeDolGI',haberDolGI='$haberDolGI',
ObsGO='$ObsGO',debeGO='$debeGO',haberGO='$haberGO',debeDolGO='$debeDolGO',haberDolGO='$haberDolGO',
ObsTD='$ObsTD',debeTD='$debeTD',haberTD='$haberTD',debeDolTD='$debeDolTD',haberDolTD='$haberDolTD',
ObsPCont='$ObsPCont',debePCont='$debePCont',haberPCont='$haberPCont',debeDolPCont='$debeDolPCont',haberDolPCont='$haberDolPCont',
ObsDC='$ObsDC',debeDC='$debeDC',haberDC='$haberDC',debeDolDC='$debeDolDC',haberDolDC='$haberDolDC',
ObsG='$ObsG',debeG='$debeG',haberG='$haberG',debeDolG='$debeDolG',haberDolG='$haberDolG',
ObsA='$ObsA',debeA='$debeA',haberA='$haberA',debeDolA='$debeDolA',haberDolA='$haberDolA',
ObsPC='$ObsPC',debePC='$debePC',haberPC='$haberPC',debeDolPC='$debeDolPC',haberDolPC='$haberDolPC',
ObsDP='$ObsDP',debeDP='$debeDP',haberDP='$haberDP',debeDolDP='$debeDolDP',haberDolDP='$haberDolDP',
ObsPAA='$ObsPAA',debePAA='$debePAA',haberPAA='$haberPAA',debeDolPAA='$debeDolPAA',haberDolPAA='$haberDolPAA',
ObsAlm='$ObsAlm',debeAlm='$debeAlm',haberAlm='$haberAlm',debeDolAlm='$debeDolAlm',haberDolAlm='$haberDolAlm',
ObsTra='$ObsTra',debeTra='$debeTra',haberTra='$haberTra',debeDolTra='$debeDolTra',haberDolTra='$haberDolTra',
ObsEst='$ObsEst',debeEst='$debeEst',haberEst='$haberEst',debeDolEst='$debeDolEst',haberDolEst='$haberDolEst',
ObsOtro='$ObsOtro',
ObsCC='$ObsCC',debeCC='$debeCC',haberCC='$haberCC',debeDolCC='$debeDolCC',haberDolCC='$haberDolCC',
ObsFTrans='$ObsFTrans',
ObsTHD='$ObsTHD',debeTHD='$debeTHD',haberTHD='$haberTHD',debeDolTHD='$debeDolTHD',haberDolTHD='$haberDolTHD',
ObsEDS='$ObsEDS',debeEDS='$debeEDS',haberEDS='$haberEDS',debeDolEDS='$debeDolEDS',haberDolEDS='$haberDolEDS',
ObsCG='$ObsCG',debeCG='$debeCG',haberCG='$haberCG',debeDolCG='$debeDolCG',haberDolCG='$haberDolCG',
ObsEDS='$ObsEDS',debeEDS='$debeEDS',haberEDS='$haberEDS',debeDolEDS='$debeDolEDS',haberDolEDS='$haberDolEDS',
ObsTHD='$ObsTHD',debeTHD='$debeTHD',haberTHD='$haberTHD',debeDolTHD='$debeDolTHD',haberDolTHD='$haberDolTHD',
ObsCP='$ObsCP' where id_carga=$id_carga";
if($conexion->query($query)===true){
	header("location: Formulario.php");
}else{
	die('error al insertar datos'.$conexion->error);
}
?>